[SPBU-21.B10] Task1.3 Kargin Gleb
Belgrak/SPBU_homeworks pull request #4
Opened 2021-09-18 19:11 UTC by Belgrak

2021-09-19 16:15 UTC, SpirinEgor requested changes
Решение верное, но странный if смущает меня :(

2021-09-19 16:15 UTC, SpirinEgor commented on homework1/task_3.c
> +            printf("Измененный массив: ");
А зачем этот if внутри цикла? Ты же можешь вывести сообщение перед циклом просто.

2021-09-19 16:21 UTC, Belgrak commented on homework1/task_3.c
> +            printf("Измененный массив: ");
Просто если пользователь введет размер массива 0, то нечего вводить и выводить, и тогда эта фраза будет не нужна. А так с ifом она появляется, когда гарантировано есть результат.

2021-09-22 12:25 UTC, SpirinEgor approved these changes
С if и размер массива 0 хорошее замечание с твоей стороны. Но надо понимать, что проверка корректности массива и работа с ним разные вещи. Не надо стараться под один цикл и т.п. загнать. Правильно все поправил.

2021-09-22 12:25 UTC, merged