[SPBU-21.B10] Task2.2 Kargin Gleb
Belgrak/SPBU_homeworks pull request #9
Opened 2021-10-06 20:24 UTC by Belgrak

2021-10-06 20:30 UTC, Belgrak commented on library/commonUtils/linkedList.c
> +    LinkedListElement* newElement = malloc(sizeof(LinkedListElement));
На 3 команде программа останавливается из-за SIGABRT, вроде проблема с памятью, но я уже не первый день смотрю и все не вижу(

2021-10-13 23:45 UTC, ArtyomLobanov requested changes

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    }
Во-первых, скобки не по [стайлгайду](https://webkit.org/code-style-guidelines/#braces)
Во-вторых, разве так
```cpp
for (int i = 0; i < indexEnd - indexStart; i++)
    newArray[i] = array[indexStart + i];
```
или так
```cpp
for (int i = indexStart; i < indexEnd; i++)
    newArray[i - indexStart] = array[i];
```
или даже так
```cpp
for (int i = indexStart, j = 0; i < indexEnd; i++, j++)
    newArray[j] = array[i];
```
читать не проще? 

В-третьих, есть встроенная функция [memcpy](https://docs.microsoft.com/ru-ru/cpp/c-runtime-library/reference/memcpy-wmemcpy?view=msvc-160) – для копирования данных можно пользоваться ей.

В-четвёртых, обычно в программировании принято использовать полуинтервалы. Т.е. если есть строка s="abacaba", то какая-нибудь стандартная функция `substring(s, 2, 4)` вернёт "ac" т.е. символы со второго включительно по четвёртый невключительно. Из плюсов такого подхода:
1. Просто считать длину – полуинтервал [a; b) содержит ровно b-a элементов
2. Легко делить полуинтервал на несколько. Скажем, при бинарном поиске полуинтервал [L; R) делится на два полуинтервала [L; M) и [M; R), а не на [L;M] и [M + 1; R] как при работе с отрезками.
Я не совсем понял, какую семантику функции sliceArray вы планировали, но если вы хотели получить полуинтервал [indexStart; indexEnd), то в for-е должно быть строгое неравенство,  если хотели скопировать интервал включая indexEnd, то нужно было выделять `(indexEnd - indexStart + 2)` памяти т.к. последним в любой строке должен быть нулевой символ.

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +        return "";
Плохая идея. Как мне теперь узнать, нужно ли освобождать память из-под строки, которую вернула функция sliceArray? Если подстрока получилась пустая, то вернётся указатель на строковую константу, которая лежит в статической области памяти и при попытке её освободить программа скорее всего упадёт.

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +void delete (LinkedList* list, char start[128], char end[128], char* array)
Массивы нельзя передать по значению. В вашем случае объявление абсолютно эквивалентно такой записи:
```cpp
void delete(LinkedList* list, char* start, char* end, char* array)
```
Число 128 не несёт никакой смысловой нагрузки и только сбивает с толку. Если я передам туда массив длины 2 или 200, то ни во время компиляции, ни во время исполнения никаких ошибок не произойдёт.

Скажем, вот такая программа
```cpp
void foo(int a[10]) {
    a[1] = 10;
}

int main()
{
    int a[2] = {0, 1};
    foo(a);
    printf("%d\n", a[1]);
    return 0;
}
```
Спокойно отработает и выведет `10`

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +void delete (LinkedList* list, char start[128], char end[128], char* array)
И, кстати, у вас пробел лишний

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    int indexEndPlusOne = strstr(sliceArray(array, (int)(indexStartMinusOne + strlen(start) + 1), (int)strlen(array) - 1), end) - array + strlen(end) + 1;
Во-первых, у вас тут утечка памяти т.к. sliceArray выделяет память на куче, а вы здесь не очищаете память и никак не сохраняете указатель.
Во-вторых, зачем создавать копию суффикса строки, чтобы искать там строку end? strstr принимает два указателя на последовательности символов, заканчивающиеся нулём. `char* suffix = strstr(array, start) + strlen(start)` вполне себе валидный указатель на такую последовательность.

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    strcat(result, sliceArray(array, indexEndPlusOne, (int)strlen(array) - 1));
[strcat](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcat-wcscat-mbscat?view=msvc-160) не выделяет новую память. Она просто дописывает в конец первой строки вторую, подразумевая, что пользователь самостоятельно убедился, что в первой строке достаточно свободного места. В вашем случае это не так: для хранения result выделено ровно столько памяти, сколько было необходимо. Таким образом, при дописывании чего-либо в конец строки result вы выходите за рамки выделенной памяти и должны рано или поздно словить segmentation fault

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    int lengthOriginalArray = 0, logsCount = 0;
Создавать несколько переменных на одной строке – дурной тон. Кроме того, что это затрудняет отслеживание использования переменных, в С/C++ это ещё и может вводить читателя в заблуждение в некоторых случаях. Например, в конструкции `int* a, b;` переменная `а` имеет тип `int*`, а переменная `b` – `int`

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    char* originalArray = calloc(lengthOriginalArray, sizeof(char));
Забыли выделить место под нулевой символ

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +            delete (list, firstArgument, secondArgument, array);
лишний пробел

2021-10-13 23:45 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    int indexStartMinusOne = strstr(array, start) - array - 1;
А вдруг искомая последовательность не нашлась? Если я не накосячил, то в тестовом примере такой ситуации возникнуть не должно, но такое может случиться если из-за ошибки в реализации какой-то из операций вы получаете стоку, отличную от запланированной. Простая проверка поможет отловить такую ситуацию.

2021-10-13 23:45 UTC, ArtyomLobanov commented on library/commonUtils/linkedList.c
> +void putDna(struct LinkedList* list, const char* data)
Я планировал, что вы будете использовать связный список для непосредственного хранения символов ДНК. В задании была формулировка 
>Для хранения ДНК предлагается использовать связный список.
Я готов допустить, что вы интерпретировали это как "хранить итерации ДНК в списке". Формально под формулировку это подходит, так что если вам так удобнее, можете работать со строками. Но зачем тогда упоминать DNA в реализации списка? Сам по себе он же просто хранит строки. Может завтра мы будем хранить в нём, скажем, какие-нибудь имена людей.

2021-10-16 14:23 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    free(array);
Но в array вы храните указатель на строку, хранящуюся в списке. В итоге вы уничтожаете последнюю записанную строку (т.е. итоговую искомую ДНК), а затем в main-е обращаетесь к ней при записи в файл. Это Undefined Behaviour.

2021-10-16 14:24 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +    char command[128] = "", firstArgument[128] = "", secondArgument[128] = "";
Объявлять несколько переменных на одной строке – дурной тон. Во-первых, это усложняет визуальное отслеживание использования переменной. Во-вторых, в некоторых случаях это может ввести читателя в заблуждение или привести к ошибке. Например, при записи `int* a, b;` переменная `a` будет иметь тип `int*`, а переменная `b` тип `int`.

2021-10-16 14:28 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +        printf("Error handled. Error in a log command.");
Перед завершением программы нужно закрыть файлы и очистить память.

2021-10-16 14:41 UTC, ArtyomLobanov commented on homework2/task2_2.c
> +        result = realloc(result, (strlen(result) + strlen(fragment) + 1) * sizeof(char));
Это потенциальная утечка памяти. Если realloc не сможет найти достаточно памяти, то вернётся NULL. Вы перезапишите прошлый указатель и уже не сможете освободить кусок памяти, выделенный в sliceArray.

2021-12-23 11:40 UTC, ArtyomLobanov commented
Ок

2021-12-23 11:41 UTC, ArtyomLobanov approved these changes

2021-12-25 12:34 UTC, merged